version: "3.8"

services:
  nginx:
    image: mujimoyen/jobplus-nginx:latest
    ports:
      - "80:80" # Expose Nginx on port 80
    restart: always
    deploy:
      replicas: 2
      placement:
        constraints: [node.role == worker]
      update_config:
        order: start-first
    networks:
      - shared_swarm_network

  jobplus-postgres:
    image: mujimoyen/jobplus-postgres:latest
    volumes:
      - /mnt/shared_storage/postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: jobplus_user
      POSTGRES_PASSWORD: D3vB*tWsmP3@6#A!
      POSTGRES_DB: jobplus_prod
    networks:
      - shared_swarm_network
    deploy:
      replicas: 4
      placement:
        constraints: [node.role == worker]

  visualizer:
    image: dockersamples/visualizer
    #ports:
    # - "8500:8080" # Expose the visualizer on port 8500
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - shared_swarm_network
    deploy:
      placement:
        constraints: [node.role == manager]

  etcd:
    image: mujimoyen/jobplus-etcd:latest
    ports:
      - "2379:2379" # For client communication
      - "2380:2380" # For other etcd nodes communication
    volumes:
      # - '/mnt/shared_storage/etcd-data:/etcd-data'
      - etcd_data:/etcd-data
    networks:
      - shared_swarm_network
    deploy:
      placement:
        constraints: [node.role == manager]

  ctl:
    image: mujimoyen/jobplus-stolon:latest
    environment:
      - ROLE=ctl
    networks:
      - shared_swarm_network
    deploy:
      placement:
        constraints: [node.role == manager]
volumes:
  etcd_data:

networks:
  shared_swarm_network:
    external: true
