---
- name: Setup Common Tasks & Gluster Install
  hosts: servers
  become: true
  roles:
    - common_tasks
    - gluster_install

- name: Gluster Shared Volume
  hosts: swarm_managers[0]
  become: true
  roles:
    - gluster_shared_volume
  tags:
    - swarm_shared_volume

- name: Mount GlusterFS Volume on all Nodes
  hosts: servers
  become: true
  roles:
    - gluster_mount_volume

- name: Swarm Initialize
  hosts: swarm_managers[0]
  become: true
  roles:
    - swarm_initialize
  tags:
    - swarm_initialize

- name: Swarm Deploy
  hosts: swarm_managers[0]
  become: true
  roles:
    - swarm_deploy
  tags:
    - swarm_deploy

- name: Join Swarm as workers
  hosts: swarm_workers
  become: true
  roles:
    - join_swarm
  tags:
    - add_workers_to_swarm
