swarm_manager_public_ip: "46.101.1.250"
swarm_worker_join_token: "SWMTKN-1-47skgzjsdjj9csp3unq1a51iwev3sp9nb1apxai15v1r3y64ms-ew9b0zvstfsz6bdzqveta9oob"
swarm_manager_join_token: "SWMTKN-1-47skgzjsdjj9csp3unq1a51iwev3sp9nb1apxai15v1r3y64ms-3kkpuyrgkp991cd205t8c0frc"
