swarm_manager_public_ip: "143.110.160.39"
swarm_worker_join_token: "SWMTKN-1-5gex9mqa7jovg6f1au03xzr45hnu9psvkycyfdnr53ai1gtodf-3puwoio06jir12sw1yj0paodw"
swarm_manager_join_token: "SWMTKN-1-5gex9mqa7jovg6f1au03xzr45hnu9psvkycyfdnr53ai1gtodf-0ntcob0lzzs1ffdk211l6mv7v"
