swarm_manager_public_ip: "167.172.53.215"
swarm_worker_join_token: "SWMTKN-1-1p1zflyhox0ezrt9q0hz7wah65e7g9djruj68q23crj0i36non-d8qqj16dc6uzyt7flh6oh7okg"
swarm_manager_join_token: "SWMTKN-1-1p1zflyhox0ezrt9q0hz7wah65e7g9djruj68q23crj0i36non-ejsrf52sohkason7d2dtwmsci"
